### ISSUE TITLE
Errors on install related to promise

### ISSUE THREAD

**Issue by DocBradfordSoftware** [michaeloryl/angular2-bootstrap4-oauth2-webpack#1]
(1,10): error TS2661: Cannot re-export name that is not defined in the module.

ERROR in ./~/angular2/src/facade/async.js
Module not found: Error: Cannot resolve module 'rxjs/observable/fromPromise' in 
node_modules/angular2/src/facade
 @ ./~/angular2/src/facade/async.js 11:20-58

**Comment by michaeloryl** [comment]
Can you tell me what command you are executing that gives you that message?

Have you done the `npm install` command?  That will make sure that all of the dependencies have been downloaded and put in place.

**Comment by michaeloryl** [comment]
I'm guessing that you bumped up the version of Angular 2 past the beta.3 that I had in source.  Starting with the failed beta.4 release, you have to handle the typings differently.  I just released 1.0.5 of this project that takes the Angular 2 dependency up to beta.8 and deals with that TypeScript error.
