### ISSUE TITLE
Feature Inquiry: Angular CLI

### ISSUE THREAD

**Issue by domfarolino** [michaeloryl/angular2-bootstrap4-oauth2-webpack#2]
Sorry to open this up as an "issue" but I'm curious as to whether you plan to integrate the Angular CLI into this project. If so I wouldn't mind forking it and working on that myself and submitting a PR at some point..something to think about though it seems it would require getting rid of webpack.

Thanks,
Dom

**Comment by michaeloryl** [comment]
To be honest, I hadn't even looked at it until you mentioned it.  But it seems interesting.  

If you'd like to take a crack at it, I'd welcome the PR.  

The CLI might be at odds with some of the Webpack functions (like serving the application), but the generators looks promising.  If the PR looks good, maybe we could set you up as a project contributor moving forward.

**Comment by michaeloryl** [comment]
It seems that the CLI doesn't currently support the new router, which is a deal-breaker.  Once that's there, then I'd be happy to take a crack at it. Until then, I'm going to close this issue/request.

**Comment by domfarolino** [comment]
No problem. Yeah right now you have to manually create the routes as route generation with the CLI is not avail yet. When it is we can revisit this
